- name: Install Frigate
  hosts: pi5
  become: true
  tasks:
    - name: Create Frigate directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ system_user }}"
        group: "{{ system_group }}"
        mode: "0755"
      loop:
        - /data/frigate/config
        - /data/frigate/storage

    - name: Install Frigate compose file
      ansible.builtin.copy:
        src: frigate/compose.yml
        dest: /data/frigate/compose.yml
        owner: "{{ system_user }}"
        group: "{{ system_group }}"
        mode: "0600"

    - name: Frigate install config file
      ansible.builtin.copy:
        src: frigate/config.yml
        dest: /data/frigate/config/config.yml
        owner: "{{ system_user }}"
        group: "{{ system_group }}"
        mode: "0600"

    - name: Substitute frigate admin password
      ansible.builtin.replace:
        path: /data/frigate/config/config.yml
        regexp: '___FRIGATE_RTSP_PASSWORD___'
        replace: '{{ frigate_rtsp_password }}'

    - name: Substitute mosquitto frigate password
      ansible.builtin.replace:
        path: /data/frigate/config/config.yml
        regexp: '___MOSQUITTO_FRIGATE_PASS___'
        replace: '{{ mosquitto_frigate_pass }}'

    - name: Install Frigate service
      ansible.builtin.copy:
        src: frigate/etc/systemd/system/frigate.service
        dest: /etc/systemd/system/frigate.service
        mode: "0644"
        owner: root
        group: root

    - name: Enable traefik service
      ansible.builtin.service:
        name: frigate
        enabled: true

    - name: Start service frigate, if not started
      ansible.builtin.service:
        name: frigate
        state: restarted
