- name: Install Home Assistant
  hosts: pi5
  become: true
  tasks:
    - name: Create Home Assistant directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ system_user }}"
        group: "{{ system_group }}"
        mode: "0755"
      loop:
        - /data/home-assistant

    - name: Install Home Assistant compose file
      ansible.builtin.copy:
        src: home-assistant/compose.yml
        dest: /data/home-assistant/compose.yml
        owner: "{{ system_user }}"
        group: "{{ system_group }}"
        mode: "0600"

    - name: Substitute P1 usb id
      ansible.builtin.replace:
        path: /data/home-assistant/compose.yml
        regexp: '___USB_P1_ID___'
        replace: '{{ usb_p1_id }}'

    - name: Substitute Modbus usb id
      ansible.builtin.replace:
        path: /data/home-assistant/compose.yml
        regexp: '___USB_MODBUS_ID___'
        replace: '{{ usb_modbus_id }}'

    - name: Substitute Zigbee usb id
      ansible.builtin.replace:
        path: /data/home-assistant/compose.yml
        regexp: '___USB_ZIGBEE_ID___'
        replace: '{{ usb_zigbee_id }}'

    - name: Substitute DNS 1
      ansible.builtin.replace:
        path: /data/home-assistant/compose.yml
        regexp: '___DNS_1___'
        replace: '{{ dns_1 }}'

    - name: Substitute DNS 2
      ansible.builtin.replace:
        path: /data/home-assistant/compose.yml
        regexp: '___DNS_2___'
        replace: '{{ dns_2 }}'

    - name: Install Home Assistant service
      ansible.builtin.copy:
        src: home-assistant/etc/systemd/system/home-assistant.service
        dest: /etc/systemd/system/home-assistant.service
        mode: "0644"
        owner: root
        group: root

    - name: Enable service home-assistant
      ansible.builtin.service:
        name: home-assistant
        enabled: true

    - name: Start service home-assistant
      ansible.builtin.service:
        name: home-assistant
        state: restarted
