- name: Install Prometheus
  hosts: pi5
  become: true
  vars:
    app_name: "prometheus"
    app_dir: "/data/{{ app_name }}"
    app_user: "{{ ansible_user }}"
    app_group: "{{ ansible_group }}"
    docker_port_http: "9090"
    host: "{{ app_name }}.home"

  tasks:
    - name: "Get user info"
      ansible.builtin.getent:
        database: passwd
        key: "{{ app_user }}"
    - name: "Set user info as facts"
      ansible.builtin.set_fact:
        uid: "{{ ansible_facts.getent_passwd[app_user][1] }}"
        gid: "{{ ansible_facts.getent_passwd[app_user][2] }}"

    - name: "Create directories {{ app_name }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: "0755"
      loop:
        - "{{ app_dir }}"
        - "{{ app_dir }}/mqtt2prometheus"

    - name: "Install files for {{ app_name }}"
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: "0644"
      loop:
        - src: "compose.yml"
          dest: "{{ app_dir }}/compose.yml"
        - src: "prometheus.yml"
          dest: "{{ app_dir }}/prometheus.yml"
        - src: "mqtt2prometheus/config.yaml"
          dest: "{{ app_dir }}/mqtt2prometheus/config.yaml"
        - src: "mqtt2prometheus/.env"
          dest: "{{ app_dir }}/mqtt2prometheus/.env"

    - name: "Substitute secrets and variables for {{ app_name }}"
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: "{{ item.regexp }}"
        replace: '{{ item.replace }}'
      loop:
        - path: "{{ app_dir }}/compose.yml"
          regexp: "___USER___"
          replace: "{{ uid }}:{{ gid }}"
        - path: "{{ app_dir }}/compose.yml"
          regexp: "___APP_NAME___"
          replace: "{{ app_name }}"
        - path: "{{ app_dir }}/compose.yml"
          regexp: "___DOCKER_PORT_HTTP___"
          replace: '{{ docker_port_http }}'
        - path: "{{ app_dir }}/compose.yml"
          regexp: "___HOST___"
          replace: '{{ host }}'
        - path: "{{ app_dir }}/prometheus.yml"
          regexp: "__HASS_LONG_LIVED_ACCESS_TOKEN_PROMETHEUS___"
          replace: '{{ hass_long_lived_access_token_prometheus }}'

    - name: "Install service for {{ app_name }}"
      ansible.builtin.copy:
        src: "../miscelaneous/etc/systemd/system/compose.service.template"
        dest: "/etc/systemd/system/{{ app_name }}.service.tmp"
        mode: "0644"
        owner: root
        group: root

    - name: "Substitute variables for service {{ app_name }}"
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: "{{ item.regexp }}"
        replace: '{{ item.replace }}'
      loop:
        - path: "/etc/systemd/system/{{ app_name }}.service.tmp"
          regexp: "___APP_NAME___"
          replace: "{{ app_name }}"
        - path: "/etc/systemd/system/{{ app_name }}.service.tmp"
          regexp: "___APP_DIR___"
          replace: '{{ app_dir }}'

    - name: "Create / update service file"
      ansible.builtin.copy:
        remote_src: true
        src: "/etc/systemd/system/{{ app_name }}.service.tmp"
        dest: "/etc/systemd/system/{{ app_name }}.service"
        mode: "0644"
        owner: root
        group: root

    - name: Remove temporary service file
      ansible.builtin.file:
        path: "/etc/systemd/system/{{ app_name }}.service.tmp"
        state: absent

    - name: "Enable service {{ app_name }}"
      ansible.builtin.service:
        name: "{{ app_name }}"
        enabled: true

    - name: "Start service {{ app_name }}"
      ansible.builtin.service:
        name: "{{ app_name }}"
        state: restarted

    - name: "Add local dns record"
      delegate_to: localhost
      ansible.builtin.lineinfile:
        dest: ../miscelaneous/local_dns_records.list
        line: '{{ ansible_host }} {{ host }}'
        state: present
