# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "1080:80/tcp"
    environment:
      TZ: 'Europe/Amsterdam'
      WEBPASSWORD: '___WEBPASSWORD___'
    volumes:
      - '/data/pihole/etc-pihole:/etc/pihole'
      - '/data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`pihole`)"
      - "traefik.http.routers.whoami.entrypoints=web"    