# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: "pihole"
    image: "pihole/pihole:latest"
    # ports:
    #   - "53:53/tcp"
    #   - "53:53/udp"
      # Default HTTP Port
      # - "80:80/tcp"
      # # Default HTTPs Port. FTL will generate a self-signed certificate
      # - "443:443/tcp"
      # Uncomment the below if using Pi-hole as your DHCP Server
      #- "67:67/udp"
    environment:
      TZ: "Europe/Amsterdam"
      WEBPASSWORD: "___WEBPASSWORD___"
    volumes:
      - "/data/pihole/etc-pihole:/etc/pihole"
      - "/data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    restart: "unless-stopped"
    labels:
      - "traefik.docker.network=webproxy"
      - "traefik.enable=true"
      - "traefik.http.routers.___APP_NAME___.rule=Host(`___APP_NAME___.___HOSTNAME___.home`)"
      - "traefik.frontend.rule=Host:___APP_NAME___.___HOSTNAME___.home"
      - "traefik.http.routers.pihole.entrypoints=web"
      - "traefik.backend=pihole" 
      - "traefik.port=80"
      - "traefik.default.protocol=http"
      - "traefik.http.services.pihole.loadbalancer.server.port=80"
      - "traefik.tcp.services.pihole.loadbalancer.server.port=53"
      - "traefik.udp.routers.dns-udp.entrypoints=dns-udp"
      - "traefik.udp.routers.dns-udp.service=pihole"
      - "traefik.udp.services.pihole.loadbalancer.server.port=53"
    networks:
      - "local"
      - "public"

networks:
  local:
     name: "pihole"

  public:
    external: true
    name: "webproxy"