services:
  ___APP_NAME___:
    user: "___USER___"
    container_name: "___APP_NAME___"
    image: grafana/grafana
    volumes:
      - /data/grafana/provisioning:/etc/grafana/provisioning
      - /data/grafana:/var/lib/grafana
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - "traefik.backend=___APP_NAME___"
      - "traefik.docker.network=webproxy"
      - "traefik.http.routers.___APP_NAME___.rule=Host(`___APP_NAME___.home`)"
      - "traefik.frontend.rule=Host:___APP_NAME___.___HOSTNAME___.home"
      - "traefik.http.routers.___APP_NAME___.entrypoints=web"
      - "traefik.enable=true"
      - "traefik.port=___DOCKER_PORT_HTTP___"
      - "traefik.default.protocol=http"
      - "traefik.http.services.___APP_NAME___.loadbalancer.server.port=___DOCKER_PORT_HTTP___"
    networks:
      - "local"
      - "public"

  loki:
    image: grafana/loki:2.9.2
    user: "___USER___"
    container_name: "loki"
    volumes:
      - /data/grafana/loki/local-config.yaml:/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - "local"

  promtail:
    image: grafana/promtail:2.9.2
    user: "___USER___"
    container_name: "promtail"
    volumes:
      - /var/log:/var/log
      - /data/grafana/promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - "local"

networks:
  local:
     name: "___APP_NAME___"

  public:
    external: true
    name: "webproxy"