- name: Install Grafana
  hosts: pi5
  become: true
  vars:
    app_name: "grafana"
    app_dir: "/data/{{ app_name }}"
    app_user: "{{ ansible_user }}"
    app_group: "{{ ansible_group }}"
    docker_port_http: "3000"
    host: "{{ app_name }}.home"

  tasks:
    - name: "Get user info"
      ansible.builtin.getent:
        database: passwd
        key: "{{ app_user }}"
    - name: "Set uid and guid as facts"
      ansible.builtin.set_fact:
        uid: "{{ ansible_facts.getent_passwd[app_user][1] }}"
        gid: "{{ ansible_facts.getent_passwd[app_user][2] }}"

    - name: "Create directories {{ app_name }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: "0755"
      loop:
        - "{{ app_dir }}"
        - "{{ app_dir }}/loki"
        - "{{ app_dir }}/promtail"
        - "{{ app_dir }}/provisioning/datasources"

    - name: "Install files for {{ app_name }}"
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ app_dir }}/{{ item.src }}"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: "0644"
      loop:
        - src: "compose.yml"
        - src: ".env"
        - src: "provisioning/datasources/ds.yaml"
        - src: "loki/local-config.yaml"
        - src: "promtail/config.yml"

    - name: "Substitute secrets and variables for {{ app_name }}"
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: "{{ item.regexp }}"
        replace: '{{ item.replace }}'
      loop:
        - path: "{{ app_dir }}/compose.yml"
          regexp: "___USER___"
          replace: "{{ uid }}:{{ gid }}"
        - path: "{{ app_dir }}/compose.yml"
          regexp: "___APP_NAME___"
          replace: "{{ app_name }}"
        - path: "{{ app_dir }}/compose.yml"
          regexp: "___HOSTNAME___"
          replace: '{{ inventory_hostname }}'
        - path: "{{ app_dir }}/compose.yml"
          regexp: "___DOCKER_PORT_HTTP___"
          replace: '{{ docker_port_http }}'

    - name: "Install service for {{ app_name }}"
      ansible.builtin.copy:
        src: "etc/systemd/system/{{ app_name }}.service"
        dest: "/etc/systemd/system/{{ app_name }}.service"
        mode: "0644"
        owner: root
        group: root

    - name: "Enable service {{ app_name }}"
      ansible.builtin.service:
        name: "{{ app_name }}"
        enabled: true

    - name: "Start service {{ app_name }}"
      ansible.builtin.service:
        name: "{{ app_name }}"
        state: restarted

    - name: "Add local dns record"
      delegate_to: localhost
      ansible.builtin.lineinfile:
        dest: ../miscelaneous/local_dns_records.list
        line: '{{ ansible_host }} {{ host }}'
        state: present
