services:
  home-assistant:
    #privileged: true
    #user: "___USER___"
    container_name: home-assistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /data/home-assistant/development/homeassistant/components/modbus:/usr/src/homeassistant/homeassistant/components/modbus
      - /data/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
      #- /run/udev:/run/udev:ro
      #- /dev/bus:/dev/bus:ro
    restart: unless-stopped
    devices:
      - /dev/serial/by-id/___USB_MODBUS_ID___:/dev/ttyUSB0
      - /dev/serial/by-id/___USB_P1_ID___:/dev/ttyUSB1
      - /dev/serial/by-id/___USB_ZIGBEE_ID___:/dev/ttyUSB2
    device_cgroup_rules:
      - 'c 188:* rmw'
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    labels:
      - "traefik.backend=home-assistant"
      - "traefik.docker.network=webproxy"
      - "traefik.http.routers.home-assistant.rule=Host(`hass.home`)"
      - "traefik.frontend.rule=Host:hass.home"
      - "traefik.http.routers.home-assistant.entrypoints=web"
      - "traefik.enable=true"
      - "traefik.port=8123"
      - "traefik.default.protocol=http"
      - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"
    networks:
       - public
       - local
    ports:
      - "8123:8123"
    dns:
      - '___DNS_1___'
      - '___DNS_2___'

networks:
  local:
     name: home-assistant

  public:
    external: true
    name: "webproxy"