- name: OpenWrt Local DNS
  hosts: nighthawk
  gather_facts: false
  become: false
  vars:
    host_user: "{{ ansible_user }}"
    host_ssh_host: "10.0.0.1"

  tasks:
    # Since OpenWrt does not run Python we need to take a non-obvious approach here by scp-ing the file.
    - name: "Upload local dns records"
      delegate_to: localhost
      ansible.builtin.command: "scp -O ../miscelaneous/local_dns_records.list {{ host_user }}@{{ host_ssh_host }}:/etc/dnsmasq.hosts"
      tags:
        - skip_ansible_lint

    - name: "Restart dnsmasq service"
      ansible.builtin.script: "service_dnsmasq_restart.sh"
