- name: Install MediaMTX webcam
  hosts: pi4
  become: true
  vars:
    app_name: "mediamtx"
    service_name: "{{ app_name }}.movie"
    app_dir: "/data/{{ app_name }}"
    app_user: "{{ ansible_user }}"
    app_group: "{{ ansible_group }}"

  tasks:
    - name: "Create directories {{ app_name }}"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: "0755"
      loop:
        - "{{ app_dir }}"

    - name: "Install files for {{ app_name }}"
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ app_dir }}/"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: "0644"
      loop:
        - src: "movie.sh"

    - name: "Install service for {{ service_name }}"
      ansible.builtin.copy:
        src: "etc/systemd/system/{{ service_name }}.service"
        dest: "/etc/systemd/system/{{ service_name }}.service"
        mode: "0644"
        owner: root
        group: root

    - name: "Enable service {{ service_name }}"
      ansible.builtin.service:
        name: "{{ service_name }}"
        enabled: true
