services:  
  adminer:
    container_name: "adminer"
    image: adminer
    restart: always
    ports:
      - 8080
    labels:
      - "traefik.backend=___APP_NAME___"
      - "traefik.docker.network=webproxy"
      - "traefik.http.routers.___APP_NAME___.rule=Host(`___APP_NAME___.___HOSTNAME___.home`)"
      - "traefik.frontend.rule=Host:___APP_NAME___.___HOSTNAME___.home"
      - "traefik.http.routers.___APP_NAME___.entrypoints=web"
      - "traefik.enable=true"
      - "traefik.port=8080"
      - "traefik.default.protocol=http"
      - "traefik.http.services.___APP_NAME___.loadbalancer.server.port=8080"
    networks:
      - immich

networks:

  immich:
    external: true
    name: "immich"
