network:
    version: 2
    renderer: networkd

    ethernets:
        eth0:
            optional: false
            addresses: [___ETH0_IP___]
            nameservers:
                addresses: [___DNS_1___,___DNS_2___]
            routes:
                - to: default
                  via: ___GATEWAY_IP___
    wifis:
        wlan0:
            optional: true
            access-points:
                ___WIFI_SSID___:
                    password: '___WIFI_PASSWORD___'
            addresses: [___WLAN0_IP___]
            nameservers:
                addresses: [___DNS_1___,___DNS_2___]