services:
  portainer:
    container_name: "portainer"
    image: portainer/portainer-ce:latest
    ports:
      - "9443:9443"
      - "9000:9000"
      - "8000:8000"
    volumes:
        - /data/portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "traefik.backend=___APP_NAME___"
      - "traefik.docker.network=webproxy"
      - "traefik.http.routers.___APP_NAME___.rule=Host(`___APP_NAME___.___HOSTNAME___.home`)"
      - "traefik.frontend.rule=Host:___APP_NAME___.___HOSTNAME___.home"
      - "traefik.http.routers.___APP_NAME___.entrypoints=web"
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.default.protocol=http"
      - "traefik.http.services.___APP_NAME___.loadbalancer.server.port=9000"
    networks:
      - "local"
      - "public"

networks:
  local:
     name: "portainer"

  public:
    external: true
    name: "webproxy"