services:
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MONGO_USER=unifi
      - MONGO_PASS=unifi
      - MONGO_HOST=mongo-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      #- MEM_LIMIT=1024 #optional
      #- MEM_STARTUP=1024 #optional
      #- MONGO_TLS= #optional
      #- MONGO_AUTHSOURCE= #optional
    volumes:
      - /data/unifi-network-application:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      # Port 8080 is used for adopting, for now this does not yet work via Traefik
      - 8080:8080
      #- 1900:1900/udp #optional
      #- 8843:8843 #optional
      #- 8880:8880 #optional
      #- 6789:6789 #optional
      #- 5514:5514/udp #optional
    restart: unless-stopped
    labels:
      - traefik.docker.network=webproxy
      - traefik.enable=true
      - traefik.http.routers.unifi.rule=Host(`unifi.home`)
      - traefik.http.routers.unifi.entrypoints=web
      - traefik.backend=unifi
      - traefik.frontend.rule=Host:unifi.home
      - traefik.port=8443
      - traefik.default.protocol=http
      - traefik.http.services.unifi.loadbalancer.server.port=8443
      - traefik.http.services.unifi.loadbalancer.server.scheme=https
    networks:
      - unifi
      - public

  mongo-db:
    image: docker.io/mongo:latest
    container_name: unifi-mongo-db
    volumes:
      - /data/unifi-network-application/mongo-db:/data/db
      - /data/unifi-network-application/mongo-db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    restart: unless-stopped
    networks:
      - unifi

networks:
  unifi:
  public:
    external: true
    name: "webproxy"
